name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package Name (Ex: com.dts.freefiremax)"
        required: true
        default: "com.dts.freefiremax"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ATUALIZADO: v3 -> v4
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # ATUALIZADO: v3 -> v4 (E Java 17 que é o padrão atual)
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - run: |
        chmod +x ./gradlew
        # Substitui a descrição no gradle
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        # Substitui o nome do pacote no arquivo C++ (game.h)
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        # Compila
        ./gradlew :module:assembleRelease

    # ATUALIZADO: v3 -> v4 (Correção do seu erro)
    - uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
        path: out/magisk_module_release/*
        if-no-files-found: error
